CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRICE_LIST_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    LAST_UPDATED_BY VARCHAR(255) NOT NULL,
    LAST_UPDATED_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);
